name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PORT: 3000
      CLIENT_URL: http://localhost:5175
      ALLOWED_ORIGINS: http://localhost:5175
      DEBUG: false
      DRY_RUN: false
      MAINTENANCE_MODE: false

      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAINTENANCE_BYPASS_KEY: ${{ secrets.MAINTENANCE_BYPASS_KEY }}

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Render
        if: success()
        run: curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}"