name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build-test-deploy:
    env:
        MONGO_URI: ${{ secrets.MONGO_URI }}


    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests 
        env:
         MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Render
        if: success()
        run: curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}"